// ============================================================
// Oxygen Compiler v0.1 PARTLY DOCUMENTED
// ============================================================

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdbool.h>

#define MAX_LINE 1024
#define MAX_OUTPUT 10000

//UYTLUTY

char* trim(char *s) {
    while (isspace(*s)) s++;
    char *end = s + strlen(s) - 1;
    while (end > s && isspace(*end)) end--;
    end[1] = '\0';
    return s;
}

bool starts_with(char *s, char *prefix) {
    return strncmp(s, prefix, strlen(prefix)) == 0;
}

bool is_number(char *s) {
    if (*s == '-') s++;
    while (*s) if (!isdigit(*s++)) return false;
    return true;
}


// GENERATOR HERE


void generate_c_code(FILE *in, FILE *out, char *filename) {
    char line[MAX_LINE];
    int indent = 0;
    int in_function = 0;
    char func_name[64] = "";
    int has_graphics = 0;
    
    // Write C header
    fprintf(out, "// ============================================================\n");
    fprintf(out, "// Generated by Oxygen Compiler v0.1\n");
    fprintf(out, "// Source: %s\n", filename);
    fprintf(out, "// ============================================================\n\n");
    
    fprintf(out, "#include <stdio.h>\n");
    fprintf(out, "#include <stdlib.h>\n");
    fprintf(out, "#include <stdbool.h>\n");
    fprintf(out, "#include <time.h>\n");
    fprintf(out, "#include <SDL2/SDL.h>\n\n");
    
    // SDL2 globals
    fprintf(out, "// ============================================================\n");
    fprintf(out, "// SDL2 Graphics\n");
    fprintf(out, "// ============================================================\n\n");
    fprintf(out, "SDL_Window *window = NULL;\n");
    fprintf(out, "SDL_Renderer *renderer = NULL;\n");
    fprintf(out, "int window_width = 640;\n");
    fprintf(out, "int window_height = 480;\n");
    fprintf(out, "int current_r = 255;\n");
    fprintf(out, "int current_g = 255;\n");
    fprintf(out, "int current_b = 255;\n");
    fprintf(out, "int running = 1;\n\n");
    
    // Drawing functions
    fprintf(out, "void pump_events() {\n");
    fprintf(out, "    SDL_Event e;\n");
    fprintf(out, "    while (SDL_PollEvent(&e)) {\n");
    fprintf(out, "        if (e.type == SDL_QUIT) running = 0;\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n\n");
    
    fprintf(out, "void draw_pixel(int x, int y) {\n");
    fprintf(out, "    SDL_SetRenderDrawColor(renderer, current_r, current_g, current_b, 255);\n");
    fprintf(out, "    SDL_RenderDrawPoint(renderer, x, y);\n");
    fprintf(out, "}\n\n");
    
    fprintf(out, "void draw_rect(int x, int y, int w, int h) {\n");
    fprintf(out, "    SDL_Rect rect = {x, y, w, h};\n");
    fprintf(out, "    SDL_SetRenderDrawColor(renderer, current_r, current_g, current_b, 255);\n");
    fprintf(out, "    SDL_RenderFillRect(renderer, &rect);\n");
    fprintf(out, "}\n\n");
    
    fprintf(out, "void draw_circle(int cx, int cy, int radius) {\n");
    fprintf(out, "    SDL_SetRenderDrawColor(renderer, current_r, current_g, current_b, 255);\n");
    fprintf(out, "    int x = radius - 1;\n");
    fprintf(out, "    int y = 0;\n");
    fprintf(out, "    int dx = 1;\n");
    fprintf(out, "    int dy = 1;\n");
    fprintf(out, "    int err = dx - (radius << 1);\n");
    fprintf(out, "    while (x >= y) {\n");
    fprintf(out, "        SDL_RenderDrawPoint(renderer, cx + x, cy + y);\n");
    fprintf(out, "        SDL_RenderDrawPoint(renderer, cx + y, cy + x);\n");
    fprintf(out, "        SDL_RenderDrawPoint(renderer, cx - y, cy + x);\n");
    fprintf(out, "        SDL_RenderDrawPoint(renderer, cx - x, cy + y);\n");
    fprintf(out, "        SDL_RenderDrawPoint(renderer, cx - x, cy - y);\n");
    fprintf(out, "        SDL_RenderDrawPoint(renderer, cx - y, cy - x);\n");
    fprintf(out, "        SDL_RenderDrawPoint(renderer, cx + y, cy - x);\n");
    fprintf(out, "        SDL_RenderDrawPoint(renderer, cx + x, cy - y);\n");
    fprintf(out, "        if (err <= 0) { y++; err += dy; dy += 2; }\n");
    fprintf(out, "        if (err > 0) { x--; dx += 2; err += dx - (radius << 1); }\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n\n");
    
    fprintf(out, "void clear_screen(int r, int g, int b) {\n");
    fprintf(out, "    SDL_SetRenderDrawColor(renderer, r, g, b, 255);\n");
    fprintf(out, "    SDL_RenderClear(renderer);\n");
    fprintf(out, "}\n\n");
    
    // Random
    fprintf(out, "int random_int(int max) {\n");
    fprintf(out, "    if (max <= 0) return rand();\n");
    fprintf(out, "    return rand() %% max;\n");
    fprintf(out, "}\n\n");
    
    // Keyboard
    fprintf(out, "const char* key_names[] = {\n");
    fprintf(out, "    \"a\",\"b\",\"c\",\"d\",\"e\",\"f\",\"g\",\"h\",\"i\",\"j\",\"k\",\"l\",\"m\",\n");
    fprintf(out, "    \"n\",\"o\",\"p\",\"q\",\"r\",\"s\",\"t\",\"u\",\"v\",\"w\",\"x\",\"y\",\"z\",\n");
    fprintf(out, "    \"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\n");
    fprintf(out, "    \"space\",\"return\",\"escape\",\"tab\",\"backspace\",\n");
    fprintf(out, "    \"up\",\"down\",\"left\",\"right\"\n");
    fprintf(out, "};\n");
    fprintf(out, "const int key_scancodes[] = {\n");
    fprintf(out, "    SDL_SCANCODE_A,SDL_SCANCODE_B,SDL_SCANCODE_C,SDL_SCANCODE_D,\n");
    fprintf(out, "    SDL_SCANCODE_E,SDL_SCANCODE_F,SDL_SCANCODE_G,SDL_SCANCODE_H,\n");
    fprintf(out, "    SDL_SCANCODE_I,SDL_SCANCODE_J,SDL_SCANCODE_K,SDL_SCANCODE_L,\n");
    fprintf(out, "    SDL_SCANCODE_M,SDL_SCANCODE_N,SDL_SCANCODE_O,SDL_SCANCODE_P,\n");
    fprintf(out, "    SDL_SCANCODE_Q,SDL_SCANCODE_R,SDL_SCANCODE_S,SDL_SCANCODE_T,\n");
    fprintf(out, "    SDL_SCANCODE_U,SDL_SCANCODE_V,SDL_SCANCODE_W,SDL_SCANCODE_X,\n");
    fprintf(out, "    SDL_SCANCODE_Y,SDL_SCANCODE_Z,\n");
    fprintf(out, "    SDL_SCANCODE_0,SDL_SCANCODE_1,SDL_SCANCODE_2,SDL_SCANCODE_3,\n");
    fprintf(out, "    SDL_SCANCODE_4,SDL_SCANCODE_5,SDL_SCANCODE_6,SDL_SCANCODE_7,\n");
    fprintf(out, "    SDL_SCANCODE_8,SDL_SCANCODE_9,\n");
    fprintf(out, "    SDL_SCANCODE_SPACE,SDL_SCANCODE_RETURN,SDL_SCANCODE_ESCAPE,\n");
    fprintf(out, "    SDL_SCANCODE_TAB,SDL_SCANCODE_BACKSPACE,\n");
    fprintf(out, "    SDL_SCANCODE_UP,SDL_SCANCODE_DOWN,SDL_SCANCODE_LEFT,SDL_SCANCODE_RIGHT\n");
    fprintf(out, "};\n");
    fprintf(out, "#define NUM_KEYS (sizeof(key_names)/sizeof(key_names[0]))\n");
    fprintf(out, "Uint8 keyboard_state[SDL_NUM_SCANCODES];\n\n");
    
    fprintf(out, "int key_down(const char *keyname) {\n");
    fprintf(out, "    for (size_t i = 0; i < NUM_KEYS; i++) {\n");
    fprintf(out, "        if (strcmp(key_names[i], keyname) == 0) {\n");
    fprintf(out, "            return keyboard_state[key_scancodes[i]];\n");
    fprintf(out, "        }\n");
    fprintf(out, "    }\n");
    fprintf(out, "    return 0;\n");
    fprintf(out, "}\n\n");
    
    // Arrays (dynamic)
    fprintf(out, "// ============================================================\n");
    fprintf(out, "// Dynamic Arrays (used by compiled Oxygen code)\n");
    fprintf(out, "// ============================================================\n\n");
    fprintf(out, "typedef struct {\n");
    fprintf(out, "    char name[32];\n");
    fprintf(out, "    int *values;\n");
    fprintf(out, "    int size;\n");
    fprintf(out, "    int capacity;\n");
    fprintf(out, "} Array;\n\n");
    
    fprintf(out, "Array arrays[100];\n");
    fprintf(out, "int array_count = 0;\n\n");
    
    fprintf(out, "Array* get_array(char *name) {\n");
    fprintf(out, "    for (int i = 0; i < array_count; i++) {\n");
    fprintf(out, "        if (strcmp(arrays[i].name, name) == 0) return &arrays[i];\n");
    fprintf(out, "    }\n");
    fprintf(out, "    return NULL;\n");
    fprintf(out, "}\n\n");
    
    fprintf(out, "Array* get_or_create_array(char *name) {\n");
    fprintf(out, "    Array *a = get_array(name);\n");
    fprintf(out, "    if (a) return a;\n");
    fprintf(out, "    a = &arrays[array_count++];\n");
    fprintf(out, "    strcpy(a->name, name);\n");
    fprintf(out, "    a->values = NULL;\n");
    fprintf(out, "    a->size = 0;\n");
    fprintf(out, "    a->capacity = 0;\n");
    fprintf(out, "    return a;\n");
    fprintf(out, "}\n\n");
    
    fprintf(out, "void array_append(Array *a, int value) {\n");
    fprintf(out, "    if (a->size >= a->capacity) {\n");
    fprintf(out, "        a->capacity = a->capacity == 0 ? 4 : a->capacity * 2;\n");
    fprintf(out, "        a->values = realloc(a->values, a->capacity * sizeof(int));\n");
    fprintf(out, "    }\n");
    fprintf(out, "    a->values[a->size++] = value;\n");
    fprintf(out, "}\n\n");
    
    fprintf(out, "int array_size(char *name) {\n");
    fprintf(out, "    Array *a = get_array(name);\n");
    fprintf(out, "    return a ? a->size : 0;\n");
    fprintf(out, "}\n\n");
    
    fprintf(out, "int array_get(char *name, int index) {\n");
    fprintf(out, "    Array *a = get_array(name);\n");
    fprintf(out, "    if (!a || index < 0 || index >= a->size) return 0;\n");
    fprintf(out, "    return a->values[index];\n");
    fprintf(out, "}\n\n");
    
    fprintf(out, "void array_set(char *name, int index, int value) {\n");
    fprintf(out, "    Array *a = get_array(name);\n");
    fprintf(out, "    if (!a || index < 0 || index >= a->size) return;\n");
    fprintf(out, "    a->values[index] = value;\n");
    fprintf(out, "}\n\n");
    
    
    fprintf(out, "// ============================================================\n");
    fprintf(out, "// MAIN\n");
    fprintf(out, "// ============================================================\n\n");
    fprintf(out, "int main(int argc, char *argv[]) {\n");
    fprintf(out, "    srand(time(NULL));\n");
    fprintf(out, "    memset(keyboard_state, 0, sizeof(keyboard_state));\n\n");
    
    // Paerse and generate code for each line
    while (fgets(line, sizeof(line), in)) {
        char *trimmed = trim(line);
        if (strlen(trimmed) == 0 || strncmp(trimmed, "//", 2) == 0) {
            // pass comments through
            fprintf(out, "    // %s\n", trimmed);
            continue;
        }
        
        //window
        if (starts_with(trimmed, "window ")) {
            char *rest = trimmed + 7;
            while (*rest && isspace(*rest)) rest++;
            char *num1 = rest;
            while (*rest && !isspace(*rest)) rest++;
            if (*rest) *rest++ = '\0';
            while (*rest && isspace(*rest)) rest++;
            char *num2 = rest;
            while (*rest && !isspace(*rest)) rest++;
            if (*rest) *rest = '\0';
            int w = atoi(num1), h = atoi(num2);
            
            has_graphics = 1;
            fprintf(out, "    // --- window %d %d ---\n", w, h);
            fprintf(out, "    if (SDL_Init(SDL_INIT_VIDEO) < 0) { printf(\"SDL2 init failed\\n\"); return 1; }\n");
            fprintf(out, "    window = SDL_CreateWindow(\"Oxygen Game\", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, %d, %d, SDL_WINDOW_SHOWN);\n", w, h);
            fprintf(out, "    renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);\n");
            fprintf(out, "    if (!renderer) renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_SOFTWARE);\n");
            fprintf(out, "    window_width = %d; window_height = %d; running = 1;\n\n", w, h);
            continue;
        }
        
       
        if (starts_with(trimmed, "pixel ")) {
            char *rest = trimmed + 6;
            while (*rest && isspace(*rest)) rest++;
            char *num1 = rest;
            while (*rest && !isspace(*rest)) rest++;
            if (*rest) *rest++ = '\0';
            while (*rest && isspace(*rest)) rest++;
            char *num2 = rest;
            while (*rest && !isspace(*rest)) rest++;
            if (*rest) *rest = '\0';
            fprintf(out, "    draw_pixel(%s, %s);\n", num1, num2);
            fprintf(out, "    SDL_RenderPresent(renderer);\n");
            continue;
        }
        
        
        if (starts_with(trimmed, "rect ")) {
            char *rest = trimmed + 5;
            char *nums[4];
            for (int i = 0; i < 4; i++) {
                while (*rest && isspace(*rest)) rest++;
                nums[i] = rest;
                while (*rest && !isspace(*rest)) rest++;
                if (*rest) *rest++ = '\0';
            }
            fprintf(out, "    draw_rect(%s, %s, %s, %s);\n", nums[0], nums[1], nums[2], nums[3]);
            fprintf(out, "    SDL_RenderPresent(renderer);\n");
            continue;
        }
        

        if (starts_with(trimmed, "circle ")) {
            char *rest = trimmed + 7;
            char *nums[3];
            for (int i = 0; i < 3; i++) {
                while (*rest && isspace(*rest)) rest++;
                nums[i] = rest;
                while (*rest && !isspace(*rest)) rest++;
                if (*rest) *rest++ = '\0';
            }
            fprintf(out, "    draw_circle(%s, %s, %s);\n", nums[0], nums[1], nums[2]);
            fprintf(out, "    SDL_RenderPresent(renderer);\n");
            continue;
        }
        
        
        if (starts_with(trimmed, "color ")) {
            char *rest = trimmed + 6;
            char *nums[3];
            for (int i = 0; i < 3; i++) {
                while (*rest && isspace(*rest)) rest++;
                nums[i] = rest;
                while (*rest && !isspace(*rest)) rest++;
                if (*rest) *rest++ = '\0';
            }
            fprintf(out, "    current_r = %s; current_g = %s; current_b = %s;\n", nums[0], nums[1], nums[2]);
            continue;
        }
        
      
        if (starts_with(trimmed, "clear ")) {
            char *rest = trimmed + 6;
            char *nums[3];
            for (int i = 0; i < 3; i++) {
                while (*rest && isspace(*rest)) rest++;
                nums[i] = rest;
                while (*rest && !isspace(*rest)) rest++;
                if (*rest) *rest++ = '\0';
            }
            fprintf(out, "    clear_screen(%s, %s, %s);\n", nums[0], nums[1], nums[2]);
            continue;
        }
        
        //UPDATE
        if (strcmp(trimmed, "update") == 0) {
            fprintf(out, "    SDL_RenderPresent(renderer);\n");
            fprintf(out, "    pump_events();\n");
            continue;
        }
        
        //DELAY
        if (starts_with(trimmed, "delay ")) {
            char *rest = trimmed + 6;
            while (*rest && isspace(*rest)) rest++;
            fprintf(out, "    SDL_Delay(%s);\n", rest);
            fprintf(out, "    pump_events();\n");
            continue;
        }
        
        //CLOSE
        if (strcmp(trimmed, "close") == 0) {
            fprintf(out, "    SDL_DestroyRenderer(renderer);\n");
            fprintf(out, "    SDL_DestroyWindow(window);\n");
            fprintf(out, "    SDL_Quit();\n");
            fprintf(out, "    return 0;\n");
            continue;
        }
        
        //KEYDOWN
        if (strstr(trimmed, "key_down(")) {
            char *start = strstr(trimmed, "key_down(");
            char *end = strchr(start, ')');
            if (end) {
                *end = '\0';
                char *inside = start + 9;
                while (isspace(*inside)) inside++;
                if (*inside == '"') {
                    inside++;
                    char keyname[64];
                    int i = 0;
                    while (*inside && *inside != '"') keyname[i++] = *inside++;
                    keyname[i] = '\0';
                    fprintf(out, "    key_down(\"%s\")", keyname);
                }
            }
            continue;
        }
        
        // ----- RANDOM -----
        if (strstr(trimmed, "random(")) {
            // Replace random() with random_int()
            char *src = trimmed;
            char out_buf[MAX_LINE] = {0};
            char *dst = out_buf;
            while (*src) {
                if (strncmp(src, "random(", 7) == 0) {
                    strcpy(dst, "random_int(");
                    dst += 10;
                    src += 7;
                } else {
                    *dst++ = *src++;
                }
            }
            *dst = '\0';
            
        }
        
        // ----- SAY -----
        if (starts_with(trimmed, "say ")) {
            char *arg = trim(trimmed + 4);
            if (arg[0] == '"') {
                // String literal with possible concat
                fprintf(out, "    printf(\"");
                char *p = arg + 1;
                while (*p && *p != '"') {
                    if (*p == '+') {
                        // Skip plus and spaces
                        p++;
                        while (isspace(*p)) p++;
                        // Check for variable
                        if (*p == '"') {
                            // String concatenation - skip
                            p++;
                            continue;
                        }
                        // Variable name
                        char var_name[64];
                        int i = 0;
                        while (*p && !isspace(*p) && *p != '+' && *p != '"') {
                            var_name[i++] = *p++;
                        }
                        var_name[i] = '\0';
                        fprintf(out, "\"");
                        fprintf(out, "); printf(\"%%d\", %s); printf(\"", var_name);
                        if (*p == '"') p++;
                        continue;
                    }
                    fputc(*p, out);
                    p++;
                }
                fprintf(out, "\\n\");\n");
            } else {
              
                fprintf(out, "    printf(\"%%d\\n\", %s);\n", arg);
            }
            continue;
        }
        //From now on there vill be no document. READ THIS!
        //ASSIGNMENT (x is value)
        char *is_pos = strstr(trimmed, " is ");
        if (is_pos) {
            *is_pos = '\0';
            char *var_name = trim(trimmed);
            char *expr = trim(is_pos + 4);
         

            if (expr[0] == '[') {
                fprintf(out, "    {\n");
                fprintf(out, "        Array *a = get_or_create_array(\"%s\");\n", var_name);
                fprintf(out, "        a->size = 0;\n");
                char *p = expr + 1;
                int idx = 0;
                while (*p && *p != ']') {
                    while (isspace(*p)) p++;
                    if (*p == ']') break;
                    char num_str[32];
                    int i = 0;
                    while (*p && *p != ',' && *p != ']' && !isspace(*p)) {
                        num_str[i++] = *p++;
                    }
                    num_str[i] = '\0';
                    if (strlen(num_str) > 0) {
                        fprintf(out, "        array_append(a, %s);\n", num_str);
                    }
                    if (*p == ',') p++;
                }
                fprintf(out, "    }\n");
                continue;
            }
            
           
            char *bracket = strchr(var_name, '[');
            if (bracket) {
                char *close = strchr(bracket, ']');
                if (close) {
                    *bracket = '\0';
                    char *arr_name = trim(var_name);
                    char *index_str = trim(bracket + 1);
                    *close = '\0';
                    fprintf(out, "    array_set(\"%s\", %s, %s);\n", arr_name, index_str, expr);
                    continue;
                }
            }
            
          
            fprintf(out, "    int %s = %s;\n", var_name, expr);
            continue;
        }
        
        
        if (starts_with(trimmed, "if ")) {
            char *then_pos = strstr(trimmed, " then");
            if (then_pos) {
                *then_pos = '\0';
                char *cond = trim(trimmed + 3);
                char *then_body = trim(then_pos + 5);
                fprintf(out, "    if (%s) {\n", cond);
                if (strlen(then_body) > 0) {
                    
                    fprintf(out, "        // %s\n", then_body);
                }
                continue;
            }
        }
        
        if (strcmp(trimmed, "end") == 0) {
            fprintf(out, "    }\n");
            continue;
        }
        
    
        if (strcmp(trimmed, "else") == 0) {
            fprintf(out, "    } else {\n");
            continue;
        }
        
   
        if (starts_with(trimmed, "else if ")) {
            char *then_pos = strstr(trimmed, " then");
            if (then_pos) {
                *then_pos = '\0';
                char *cond = trim(trimmed + 7);
                fprintf(out, "    } else if (%s) {\n", cond);
                continue;
            }
        }
        
        
        if (starts_with(trimmed, "while ")) {
            char *cond = trim(trimmed + 6);
            fprintf(out, "    while (%s) {\n", cond);
            continue;
        }
        
       
        if (starts_with(trimmed, "for ")) {
            char *from_pos = strstr(trimmed, " from ");
            char *to_pos = strstr(trimmed, " to ");
            if (from_pos && to_pos) {
                *from_pos = '\0';
                char *var_name = trim(trimmed + 4);
                char *from_str = trim(from_pos + 6);
                *to_pos = '\0';
                char *to_str = trim(to_pos + 4);
                
              
                char *step_pos = strstr(to_str, " step ");
                int has_step = 0;
                char step_str[32] = "1";
                if (step_pos) {
                    has_step = 1;
                    *step_pos = '\0';
                    char *step = trim(step_pos + 6);
                    strcpy(step_str, step);
                }
                
                fprintf(out, "    for (int %s = %s; %s <= %s; %s += %s) {\n", 
                        var_name, from_str, var_name, to_str, var_name, step_str);
                continue;
            }
        }
        
       
        if (starts_with(trimmed, "function ")) {
            char *rest = trimmed + 9;
            char fname[64];
            int i = 0;
            while (*rest && !isspace(*rest) && *rest != '(') fname[i++] = *rest++;
            fname[i] = '\0';
            
          
            while (*rest && *rest != '(') rest++;
            if (*rest == '(') rest++;
            char params[256] = "";
            char param_names[64][32];
            int param_count = 0;
            while (*rest && *rest != ')') {
                while (isspace(*rest)) rest++;
                if (*rest == ')') break;
                int j = 0;
                while (*rest && !isspace(*rest) && *rest != ',' && *rest != ')') {
                    param_names[param_count][j++] = *rest++;
                }
                param_names[param_count][j] = '\0';
                if (j > 0) param_count++;
                while (*rest && (*rest == ',' || isspace(*rest))) rest++;
            }
            
         
            fprintf(out, "int %s(", fname);
            for (int j = 0; j < param_count; j++) {
                if (j > 0) fprintf(out, ", ");
                fprintf(out, "int %s", param_names[j]);
            }
            fprintf(out, ") {\n");
            in_function = 1;
            strcpy(func_name, fname);
            continue;
        }
        
        
        if (starts_with(trimmed, "return ")) {
            char *expr = trim(trimmed + 7);
            fprintf(out, "    return %s;\n", expr);
            continue;
        }
        
  
        fprintf(out, "    // %s\n", trimmed);
    }
    
    
    fprintf(out, "    return 0;\n");
    fprintf(out, "}\n");
}

// ============================================================
// MAIN
// ============================================================

int main(int argc, char *argv[]) {
    if (argc < 2) {
        printf("Usage: %s script.ox [output_name]\n", argv[0]);
        printf("Example: %s game.ox\n", argv[0]);
        printf("Example: %s game.ox mygame\n", argv[0]);
        return 1;
    }
    
    char *input_file = argv[1];
    char *output_name = argc > 2 ? argv[2] : NULL;
    char output_file[256];
    char c_file[256];
    
  
    if (output_name) {
        snprintf(c_file, sizeof(c_file), "%s.c", output_name);
        snprintf(output_file, sizeof(output_file), "%s", output_name);
    } else {
        char base[128];
        strcpy(base, input_file);
        char *dot = strrchr(base, '.');
        if (dot) *dot = '\0';
        snprintf(c_file, sizeof(c_file), "%s.c", base);
        snprintf(output_file, sizeof(output_file), "%s", base);
    }
    
    printf("🔨 Compiling Oxygen script: %s\n", input_file);
    printf("   Output C file: %s\n", c_file);
    printf("   Output binary: %s\n", output_file);
    
   
    FILE *in = fopen(input_file, "r");
    if (!in) {
        printf("Error: Cannot open input file '%s'\n", input_file);
        return 1;
    }
    

    FILE *out = fopen(c_file, "w");
    if (!out) {
        printf(" Error: Cannot create output file '%s'\n", c_file);
        fclose(in);
        return 1;
    }
    
    
    generate_c_code(in, out, input_file);
    
    fclose(in);
    fclose(out);
    
    printf("C code generated: %s\n", c_file);
    
    
    char cmd[1024];
    snprintf(cmd, sizeof(cmd), 
             "clang -O2 -Wall -Wextra -o %s %s -lSDL2 -framework Cocoa -framework OpenGL -framework CoreFoundation -framework CoreGraphics -framework IOKit -framework CoreVideo",
             output_file, c_file);
    
    printf("🔨 Compiling C to binary...\n");
    int result = system(cmd);
    if (result != 0) {
        printf("Compilation failed with exit code %d\n", result);
        return 1;
    }
    
    printf("Binary created: %s\n", output_file);
    printf("Run it: ./%s\n", output_file);
    
    return 0;
}